### ISSUE TITLE
[S52.1]: Text Grid

### ISSUE THREAD

**Issue by EnaamAlum** [Open-Study-College/osc#741] opened 2023-02-24 11:12 UTC
### Link to Epic

Epic: https://github.com/Open-Study-College/osc/issues/171

### Description

Reviewer: Matt

### Linked Tasks

#742 
#743 
#744

_No response_

**Comment by stevenbister** [comment] 2023-02-28 08:29
Duplicate of #697

**Closed by stevenbister** 2023-02-28 08:29 UTC
Labels: story, Sprint 10
